AWSTemplateFormatVersion: 2010-09-09

Description: Builds and runs the kinesis-analytics-taxi-consumer Flink application in a fully managed environment using Amazon Kinesis Data Analytics for Java Applications (amazon-kinesis-analytics-taxi-consumer)

Parameters:
  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the EC2 instance for replaying events
    ConstraintDescription: MuSt be the name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

  ClientIpAddressRange:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Description: IP address range that is able to access the EC2 instance and that gets full read and write access to the Elasticsearch Cluster and the Kibana dashboard
    MaxLength: 18
    MinLength: 9
    Type: String

  ExternalArtifactBucket:
    Description: Optional. S3 bucket that is used to store the compiled binaries and output files
    Type: String

  Release:
    Description: Github branch or release to be used for the replay application
    Type: String
    Default: master


Conditions:
  UseInternalArtifactBucket:
    !Equals [!Ref ExternalArtifactBucket, ""]


Outputs:
  ArtifactBucket:
    Description: Bucket containing the generated jar file and output files
    Value: !If [UseInternalArtifactBucket, !Ref InternalArtifactBucket, !Ref ExternalArtifactBucket]

  KinesisReplayInstance:
    Description: SSH connection to the instance that ingests trip events into the Kinesis stream
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.KinesisReplayInstance

  ProducerCommand:
    Description: Command to populate Kinesis stream with taxi trip events
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.ProducerCommand

  KibanaDashboardURL:
    Description: URL to access the Kibana dasboard
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.KibanaDashboardURL

  CloudWatchDashboardURL:
    Description: URL to access metrics in a CloudWatch dasboard
    Value: !GetAtt TaxiConsumerInfrastructure.Outputs.CloudWatchDashboardURL


Resources:
  InternalArtifactBucket:
    Condition: UseInternalArtifactBucket
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  KinesisReplayBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/yfw-useast1/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/kinesis-replay-build-pipeline.yml
      Parameters:
        ExternalArtifactBucket: !If [UseInternalArtifactBucket, !Ref InternalArtifactBucket, !Ref ExternalArtifactBucket]
        Release: !Ref Release

  TaxiConsumerBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/yfw-useast1/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/kinesis-analytics-taxi-consumer-build-pipeline.yml
      Parameters:
        ArtifactBucket: !If [UseInternalArtifactBucket, !Ref InternalArtifactBucket, !Ref ExternalArtifactBucket]
        FlinkApplicationS3Path: amazon-kinesis-analytics-taxi-consumer-0.3.0.jar
        Release: !Ref Release

  TaxiConsumerInfrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/yfw-useast1/artifacts/kinesis-analytics-taxi-consumer/cfn-templates/kinesis-analytics-taxi-consumer-infrastructure.yml
      Parameters:
        KinesisReplayCopyCommand: !GetAtt KinesisReplayBuildStack.Outputs.KinesisReplayCopyCommand
        FlinkApplicationS3Bucket: !If [UseInternalArtifactBucket, !Ref InternalArtifactBucket, !Ref ExternalArtifactBucket]
        FlinkApplicationS3Path: !GetAtt TaxiConsumerBuildStack.Outputs.FlinkApplicationS3Path
        SshKeyName: !Ref SshKeyName
        ClientIpAddressRange: !Ref ClientIpAddressRange
        Release: !Ref Release

