AWSTemplateFormatVersion: 2010-09-09

Description: Infrastructure to create opensearch

Parameters:
  ClientIpAddressRange:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: IP address range that is able to SSH into the EC2 instance and that gets full read and write access to the Elasticsearch Cluster and the Kibana dashboard
    MaxLength: 18
    MinLength: 9
    Type: String


Outputs:
  KibanaDashboardURL:
    Description: URL to access the Kibana dasboard
    Value: !Sub https://${ElasticsearchService.DomainEndpoint}/_plugin/kibana/app/kibana#/dashboard/nyc-tlc-dashboard


Resources:
  ElasticsearchService:
    Type: AWS::OpenSearchService::Domain
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - 'es:*'
          Resource: '*'
          Condition:
            IpAddress:
              'aws:SourceIp':
              - !Sub '${ClientIpAddressRange}'
      ClusterConfig:
        InstanceCount: 1
        InstanceType: t3.medium.search
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 100
        VolumeType: gp2
      EngineVersion: OpenSearch_1.0



Mappings:
  AWSRegionArch2AMI:
    eu-central-1:
      HVM64: ami-0f3a43fbf2d3899f7
    eu-west-1:
      HVM64: ami-07683a44e80cd32c5
    us-west-2:
      HVM64: ami-061392db613a6357b
    us-east-1:
      HVM64: ami-0de53d8956e8dcf80
    us-east-2:
      HVM64: ami-02bcbb802e03574ba
